version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@12.3.0
  shellcheck: circleci/shellcheck@3.3.0

filters: &filters
  tags:
    only: /.*/

workflows:
  lint-pack:
    jobs:
      - orb-tools/lint:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/review:
          exclude: RC010
          filters: *filters
      - shellcheck/check:
          filters: *filters
      - orb-tools/continue:
          orb_name: hugo
          pipeline_number: << pipeline.number >>
          vcs_type: << pipeline.project.type >>
          requires: [orb-tools/lint, orb-tools/pack, orb-tools/review, shellcheck/check]
          filters: *filters
