version: 2.1

orbs:
  cli: circleci/circleci-cli@0.1
  hugo: circleci/hugo@dev:alpha  # dev:alpha is used for integration tests
  orb-tools: circleci/orb-tools@9.0

parameters:
  # These pipeline parameters are required by the
  # "trigger-integration-tests-workflow" job, by default.
  run-integration-tests:
    type: boolean
    default: false
  dev-orb-version:
    type: string
    default: "dev:alpha"

workflows:
  lint_pack-validate_publish-dev:  # runs on every commit
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint
      - orb-tools/pack
      - orb-tools/publish-dev:
          # release dev version of orb, for testing & possible publishing.
          # orb will be published as dev:alpha and dev:${CIRCLE_SHA1:0:7}.
          orb-name: circleci/hugo
          requires:
            - orb-tools/pack
          context: orb-publishing
      - orb-tools/trigger-integration-tests-workflow:
          # trigger an integration workflow to test the
          # dev:${CIRCLE_SHA1:0:7} version of your orb
          name: trigger-integration-dev
          requires:
            - orb-tools/publish-dev
          context: orb-publishing
  integration-tests_prod-release:
    # This `integration-tests_prod-release` workflow will only run
    # when the run-integration-tests pipeline parameter is set to true.
    # It is meant to be triggered by the "trigger-integration-tests-workflow"
    # job, and run tests on <your orb>@dev:${CIRCLE_SHA1:0:7}.
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - integration-test-1
      - integration-test-2
      - integration-test-3

      # publish a semver version of the orb. relies on
      # the commit subject containing the text "[semver:patch|minor|major|skip]"
      # as that will determine whether a patch, minor or major
      # version will be published or if publishing should
      # be skipped.
      # e.g. [semver:patch] will cause a patch version to be published.
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: circleci/hugo
          context: orb-publishing
          add-pr-comment: true
          bot-token-variable: GHI_TOKEN
          bot-user: cpe-bot
          fail-if-semver-not-indicated: true
          publish-version-tag: true
          requires:
            - integration-test-1
            - integration-test-2
            - integration-test-3
          filters:
            branches:
              only: master

jobs:
  integration-test-1:
    executor:
      name: hugo/default
      tag: "0.78.0"
    steps:
      - run:
          name: "Check out Hugo Docs as a sample project."
          command: |
            git clone "https://github.com/gohugoio/hugoDocs.git" ~/project
            rm ~/project/content/en/content-management/related.md
      - hugo/hugo-build
      - run:
          name: "Basic Test"
          command: hugo version
  integration-test-2:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Check out Hugo Docs as a sample project."
          command: |
            git clone "https://github.com/gohugoio/hugoDocs.git" ~/project
            rm ~/project/content/en/content-management/related.md
      - hugo/install:
          version: "0.78.0"
      - hugo/hugo-build:
          asciidoc: true
      - run:
          name: "Basic Test"
          command: hugo version
  integration-test-3:
    macos:
      xcode: 11.4.1
    steps:
      - run:
          name: "Check out Hugo Docs as a sample project."
          command: |
            git clone "https://github.com/gohugoio/hugoDocs.git" ~/project
            rm ~/project/content/en/content-management/related.md
      - hugo/install:
          version: "0.78.0"
      - hugo/hugo-build
      - run:
          name: "Basic Test"
          command: hugo version
