version: 2.1
orbs:
  hugo: circleci/hugo@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.5
filters: &filters
  tags:
    only: /.*/
jobs:
  integration-test-1:
    executor:
      name: hugo/default
      tag: "0.92.2"
    steps:
      - run:
          name: "Check out Hugo Docs as a sample project."
          command: |
            git clone "https://github.com/gohugoio/hugoDocs.git" ~/project
            rm ~/project/content/en/content-management/related.md
      - hugo/hugo-build
      - run:
          name: "Basic Test"
          command: hugo version
  integration-test-2:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: "Check out Hugo Docs as a sample project."
          command: |
            git clone "https://github.com/gohugoio/hugoDocs.git" ~/project
            rm ~/project/content/en/content-management/related.md
      - hugo/install:
          version: "0.92.2"
      - hugo/hugo-build
      - run:
          name: "Basic Test"
          command: hugo version
  integration-test-3:
    macos:
      xcode: 11.4.1
    steps:
      - run:
          name: "Check out Hugo Docs as a sample project."
          command: |
            git clone "https://github.com/gohugoio/hugoDocs.git" ~/project
            rm ~/project/content/en/content-management/related.md
      - hugo/install:
          version: "0.92.2"
      - hugo/hugo-build
      - run:
          name: "Basic Test"
          command: hugo version
workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - integration-test-1:
          filters: *filters
      - integration-test-2:
          filters: *filters
      - integration-test-3:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: circleci/hugo
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - integration-test-1
            - integration-test-2
            - integration-test-3
          context: orb-publisher
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
