description: "The cibuilds/hugo Docker image."
parameters:
  hugo_version:
    description: "Specifies the hugo version to install"
    type: string
    default: "0.142.0"
docker:
  - image: cibuilds/hugo:<< parameters.hugo_version >>
