description: "The cibuilds/hugo Docker image."
parameters:
  hugo_version:
    description: "Specifies the hugo version to install"
    type: string
    default: "latest"
docker:
  - image: chainguard/hugo:<< parameters.hugo_version >>
